--ADDITIONAL SELECT -OPTION
--1
SELECT  STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "학생 주소"
FROM TB_STUDENT
ORDER BY 1;

--2
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT
ORDER BY 2 DESC;

--3
SELECT  STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1,3) IN ('경기도', '강원도') AND (SUBSTR(STUDENT_NO,1,2) LIKE ('9%'));


--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '001'
ORDER BY 1 DESC;

SELECT DISTINCT P.PROFESSOR_NAME, P.PROFESSOR_SSN

FROM TB_PROFESSOR P JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
                            JOIN TB_CLASS E USING (CLASS_NO)
                            
WHERE E.DEPARTMENT_NO = '005'
ORDER BY 2 ;




SELECT *
FROM TB_DEPARTMENT;

SELECT * 
FROM TB_CLASS;



--5
SELECT STUDENT_NO , POINT
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NO = 'C3118100' AND TERM_NO ='200402'
ORDER BY 2 DESC;


SELECT *
FROM TB_GRADE;
--6

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM  TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2 ;

--7
 SELECT CLASS_NAME, DEPARTMENT_NAME
 FROM  TB_CLASS JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR JOIN TB_CLASS USING (DEPARTMENT_NO)
ORDER BY 2;

--9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR JOIN TB_CLASS USING (DEPARTMENT_NO)
                            JOIN TB_DEPARTMENT USING( DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY 2;


--10

SELECT  STUDENT_NO, STUDENT_NAME ,  TRUNC(AVG(POINT),1)

FROM TB_STUDENT JOIN TB_GRADE USING (STUDENT_NO)
                        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                    
WHERE DEPARTMENT_NAME = '음악학과'

GROUP BY STUDENT_NO, STUDENT_NAME;

--11
SELECT DEPARTMENT_NAME AS "학과 이름", STUDENT_NAME AS "학생이름" , PROFESSOR_NAME AS "지도교수 이름"
FROM TB_DEPARTMENT JOIN TB_STUDENT USING(DEPARTMENT_NO)
                            JOIN  TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE   STUDENT_NO = 'A313047' ;

SELECT *
FROM TB_STUDENT;


--12  ****
--정답
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
                        JOIN TB_CLASS USING (CLASS_NO)

WHERE   SUBSTR(TERM_NO, 1,4) LIKE ('2007%') AND CLASS_NAME = '인간관계론'
ORDER BY 1;



----------------쓰레기
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT JOIN TB_GRADE USING (STUDENT_NO)
                        JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME = '인간관계론' ;






SELECT STUDENT_NAME
FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NO = 'C2604100';


SELECT STUDENT_NAME, TERM_NO
FROM  TB_STUDENT  JOIN TB_GRADE USING(STUDENT_NO)
                            JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME = '인간관계론' ;


SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT  JOIN (SELECT *
                                 FROM TB_GRADE
                                WHERE CLASS_NO = (SELECT CLASS_NO
                                                            FROM TB_CLASS
                                                            WHERE CLASS_NAME = '인간관계론')) USING(STUDENT_NO)
                                                            
ORDER BY 1   ;

SELECT *
FROM TB_GRADE
WHERE CLASS_NO = (SELECT CLASS_NO
                            FROM TB_CLASS
                            WHERE CLASS_NAME = '인간관계론');

SELECT CLASS_NO
FROM TB_CLASS
WHERE CLASS_NAME = '인간관계론';

--13





SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS   OUTER LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
                         JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)   
 WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL
 ORDER BY 1,2;


SELECT *
FROM TB_CLASS;

SELECT *
FROM TB_DEPARTMENT;

SELECT *
FROM TB_CLASS_PROFESSOR;



--14 
SELECT  STUDENT_NAME, NVL(PROFESSOR_NAME ,'지도교수 미지정')
FROM TB_STUDENT 
                                left JOIN TB_DEPARTMENT  USING(DEPARTMENT_NO)
                                left JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
                                
where   department_name = '서반아어학과' ;
                                
                                
                                

SELECT *
FROM TB_PROFESSOR;

SELECT *
FROM TB_CLASS_PROFESSOR;


SELECT *
FROM TB_STUDENT
WHERE STUDENT_NAME = '남가영';


--15
SELECT STUDENT_NO,  STUDENT_NAME, DEPARTMENT_NAME , TRUNC((SELECT AVG(POINT) FROM TB_GRADE G WHERE E.STUDENT_NO = G.STUDENT_NO),1) AS "평점"
FROM TB_STUDENT E JOIN TB_DEPARTMENT USING( DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'  AND TRUNC((SELECT AVG(POINT) FROM TB_GRADE G WHERE E.STUDENT_NO = G.STUDENT_NO),1) >=4.0
ORDER BY 1;

--16

SELECT CLASS_NO, CLASS_NAME, TRUNC((SELECT AVG(POINT) FROM TB_GRADE G WHERE C.CLASS_NO = G.CLASS_NO),1) AS "AVG(POINT)"
FROM TB_CLASS C JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE LIKE ('전공%')
ORDER BY 1;


SELECT *
FROM TB_CLASS;
--17

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');


--18 ***********************************************************



----------------여기?

SELECT STUDENT_NO, STUDENT_NAME
FROM ( 

            SELECT  STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
            FROM TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                                     JOIN TB_GRADE USING (STUDENT_NO)
            WHERE DEPARTMENT_NAME = '국어국문학과' 
            GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
            ORDER BY 4 DESC
            
        )
WHERE ROWNUM =1    ;

--------------------------------------- 아래는 뻘짓


SELECT E.STUDENT_NO, E.STUDENT_NAME 

FROM TB_STUDENT E JOIN TB_GRADE O ON (E.STUDENT_NO= O. STUDENT_NO)
                        JOIN TB_DEPARTMENT D ON(E.DEPARTMENT_NO = D.DEPARTMENT_NO)
                        
WHERE DEPARTMENT_NAME = '국어국문학과' ;
                      
                                
                                
SELECT STUDENT_NAME, DEPARTMENT_NAME, SUM(POINT)
FROM TB_STUDENTS JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
                        JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'  
GROUP BY STUDENT_NAME, DEPARTMENT_NAME
HAVING SUM(POINT) > (SELECT SUM(POINT) FROM TB_GRADE R WHERE G.STUDENT_NO = R.STUDENT_NO);                                                             
                                                                                                                
                                                                                                                
                                                                                                                
SELECT STUDENT_NAME, DEPARTMENT_NAME, SUM(POINT)
FROM TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                            JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' 
                    
HAVING    SUM(POINT) >= ANY ( SELECT SUM(POINT) FROM TB_GRADE GROUP BY STUDENT_NO)
GROUP BY STUDENT_NAME, DEPARTMENT_NAME;


SELECT *
FROM TB_STUDENT
WHERE STUDENT_NAME = '방민진';

SELECT *
FROM TB_DEPARTMENT;


SELECT *
FROM TB_GRADE;

SELECT STUDENT_NO, SUM(POINT)
FROM TB_GRADE
GROUP BY STUDENT_NO;


--19
    SELECT  E. DEPARTMENT_NAME AS "게열 학과명", ROUND(  (SELECT AVG(POINT)
                                                                                                    FROM TB_GRADE 
                                                                                                    JOIN TB_STUDENT S USING(STUDENT_NO)
                                                                                                    WHERE E.DEPARTMENT_NO = S.DEPARTMENT_NO), 1) AS "전공 평점"
    
FROM TB_DEPARTMENT E
WHERE CATEGORY IN (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
ORDER BY 1;
